### ISSUE TITLE
Not an issue, rather a question 

### ISSUE THREAD

**Issue by VedadTr** [nischi/MMM-Face-Reco-DNN#119]
Im sorry for cluttering, i can delete the post after your reply if you wish so.

My questions,  is there any chance of storing the dataset files/images on a server, instead of being stored locally on the pi ?
Thanks !

**Comment by VedadTr** [comment]
Does encode.py generate any sort of ID for the profile that can be used in a database or something similar ? The goal is having a user profile in a online database, with location, to-do, desired news etc. Only thing that remains is setting up the facial reco. Any advice ?

**Comment by nischi** [comment]
hi @VedadTr 

I'm not an expert in linux, but i think you can do a mount of your network share directly to the folder for the dataset.

I do no think that the encode.py do anything like this. this will create a pickle file which contains the encoded image with the faces from your source images. with this encoded files they will learn your faces. theoreticaly we can save this also to a database. it's only a mapping between this encodings and the names. but the other script which use this to identify your face need to read it again from the database instead of the file. 

if you are familiar with python, would be nice if you can create a pull request with an optional database opt in :)
