### ISSUE TITLE
default modules not showing for strangers

### ISSUE THREAD

**Issue by mschlesinger19** [nischi/MMM-Face-Reco-DNN#36]
I have found that when the module recognizes a stranger, those modules just labeled "default" are not shown. Classes "default everyone" are shown for strangers but "default" are not shown. Is anyone else seeing this issue? Maybe my configuration is incorrect.

**Comment by nischi** [comment]
Should be like you said. I need to test that on my system and fix it.

**Comment by robertybob** [comment]
@nischi have you had the opportunity to work on this? :)

**Comment by nischi** [comment]
I'm sorry, not yet.

**Comment by majurgens** [comment]
I have a similar problem but with "everyone".
For me, 

- when there is no one in front of the camera, "default", "default everyone", "everyone default" are visible
- when I login "default everyone", "everyone default" are visible, "everyone" (ERROR) and "default" disappear, my specific modules show
- when someone else who is known logs in, "default everyone", "everyone default" are visible, "everyone" (ERROR) and "default" disappear
- when someone who is unknown logs in, "default everyone", "everyone default" are visible, "everyone" (ERROR) and "default" disappear

**Comment by majurgens** [comment]
I've looked at the code and there is actually nowhere in the code that will show the "everyone" class when a user logs in and hide it when they log out. This is why it does not work.

There is code in there that would 
- not hide "everyone" if it was already showing when someone logs in. This seems to assume that before login "everyone" would already be showing, which is not how "everyone" is supposed to work
- not show "everyone" when someone logs and there are no more logged in users. Again, the same logic that seems to assume you want to show "everyone" when someone logs out.

The code looks good for "default" so I'm not sure what the problem is as reported by mschlesinger19

I have fix up the code in my local version. I'm not sure how I would go about putting it back in github .....
