### ISSUE TITLE
Build this module or test on computer Ubuntu

### ISSUE THREAD

**Issue by phungorquan** [nischi/MMM-Face-Reco-DNN#61]
Hi nischi,

Are you using raspberry to develop this module or use the other devices?. As normally, i will try/edit/create modules on my laptop before i copy it to my raspberry. And absolute, only some modules can work without GPIO :D. 
But on laptop we have camera, Do you have any packages or tutorials to setup on Ubuntu for this module? I really want to test some solutions for better performance :D. 

Thanks!
Best regards,
Anh Quan

**Comment by nischi** [comment]
hi @phungorquan 

I use my macbook to develop this module. So i can test everything with my MagicMirror setting. The only thing i need to change in the settings of MM is to use the internal Webcam of my Macbook instead of the PiCam. 
Sorry i do not  have any packages or tutorials to setup. Only installed everything on my Macbook

Kind Regards
